### ISSUE TITLE
Checklist for 1.0.0 release

### ISSUE THREAD

**Issue by intgr** [intgr/posix-acl#29]
- [x] Write proper documentation (#27)
- [x] Add `write_default_acl` method
- [x] Avoid need for `.as_ref()` in functions that take `Path` argument
- [x] Upstream `ACL_*_ENTRY` constants into acl-sys: https://github.com/Stebalien/acl-sys/pull/3
- [x] Omit `Mask` entry in `::new()` (#37)
- [x] Use proper error type (#22)
- [x] ~~Test on FreeBSD~~ Tested #40, seems viable but deferred as #41.
- [x] ~~Implement `ExactSizeIterator` & `len()`~~ not possible with `acl.h` API :(

**Comment by intgr** [comment]
Efficient `len()` is not possible with `acl.h` API :(

**Comment by intgr** [comment]
It seems FreeBSD support is viable but requires a fair bit of work. Deferred as issue #41.
